//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMWeb {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content Content;
		
		protected System.Web.UI.WebControls.Panel formLogin;
		
		protected System.Web.UI.WebControls.Panel formTransaction;
	}
}
