//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMWeb {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content Content;
		
		protected System.Web.UI.WebControls.Panel formLogin;
		
		protected System.Web.UI.WebControls.Panel formLoginError;
		
		protected System.Web.UI.WebControls.Label lblLoginError;
		
		protected System.Web.UI.WebControls.TextBox firstNameText;
		
		protected System.Web.UI.WebControls.TextBox lastNameText;
		
		protected System.Web.UI.WebControls.TextBox PINText;
		
		protected System.Web.UI.WebControls.Panel formSignUp;
		
		protected System.Web.UI.WebControls.Panel formSignupError;
		
		protected System.Web.UI.WebControls.Label lblSignupError;
		
		protected System.Web.UI.WebControls.TextBox firstNameSignupText;
		
		protected System.Web.UI.WebControls.TextBox lastNameSignupText;
		
		protected System.Web.UI.WebControls.TextBox PINSignupText;
		
		protected System.Web.UI.WebControls.TextBox PINSignupConfirmText;
		
		protected System.Web.UI.WebControls.Panel formTransaction;
	}
}
